/* mbola mila testena soD ts mifNaraka le taille anle varchar 
	mila ovaina caractere special hafa 
	é: efa vita
*/

create table categorie(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
nom varchar(20)
)Engine=InnoDB;

create table film(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
titre varchar(50),
origine varchar(20),
realisation varchar(20),
duree varchar(10),
acteurs varchar(150),
datesortie datetime,
description varchar(1000),
cheminimg varchar(100)
)Engine=InnoDB;

create table linkFilmCat(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
idCat int,
idFilm int,
FOREIGN KEY (idCat) REFERENCES categorie(id),
FOREIGN KEY (idFilm) REFERENCES film(id)
);


create table salle(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
nom varchar(10),
numero int,
nbrPlace int
)Engine=InnoDB;

create table programme(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
idFilm int,
idSalle int,
daty date,
heureDebut varchar(5),
heureFin varchar(5),
prixUnitaire double,
prioritaire int,
FOREIGN KEY (idFilm) REFERENCES film(id),
FOREIGN KEY (idSalle) REFERENCES salle(id)
)Engine=InnoDB;


create table membre(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
pseudo varchar(20),
email varchar(20),
password varchar(20),
autorisation int,
cheminimg varchar(100)
)Engine=InnoDB;


create table reservation(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
idMembre int,
idProgramme int,
nbrPlac int,
montant double,
FOREIGN KEY (idMembre) REFERENCES membre(id),
FOREIGN KEY (idProgramme) REFERENCES programme(id)
)Engine=InnoDB;


create table commentaires(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
idFilm int,
texte varchar(100),
idMembre int,
FOREIGN KEY (idFilm) REFERENCES film(id),
FOREIGN KEY (idMembre) REFERENCES membre(id)
)Engine=InnoDB;

create table billet(
id INTEGER NOT NULL AUTO_INCREMENT primary key,
idReservation int,
FOREIGN KEY (idReservation) REFERENCES reservation(id)

);

/* categorie INSERT INTO categorie (nom) (nom) VALUES */
insert INTO categorie (nom) values ("Com&eacute\;die");
insert INTO categorie (nom) values ("Horreur");
insert INTO categorie (nom) values ("Romance");
insert INTO categorie (nom) values ("Animation");
insert INTO categorie (nom) values ("Musical");
insert INTO categorie (nom) values ("Fantastique");
insert INTO categorie (nom) values ("drame");
insert INTO categorie (nom) values ("Famille");
insert INTO categorie (nom) values ("Aventure");
insert INTO categorie (nom) values ("Action");
insert INTO categorie (nom) values ("Thriller");
insert INTO categorie (nom) values ("Policier");
insert INTO categorie (nom) values ("Historique");
insert INTO categorie (nom) values ("Science fiction");


/* films INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES */
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "ABCs of Death 2.5","Am&eacute;ricain","Travis Betz, Zac Blair","1:25","Ali Arslan, Ilker Arslan, Anastasia Baranova ","2 Août 2017(USA)","26 nouveaux courts-m&eacute;trages, 26 nouvelles façons de mourir...","abcsofdeath.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "AMOUR ET AMNÉSIE","Am&eacute;ricain","Peter Segal","1:39","Adam Sandler, Drew Barrymore, Rob Schneider plus","30 juin 2004","La vie de Henry Roth est simple. Lorsque ce v&eacute;t&eacute;rinaire sp&eacute;cialiste des animaux marins polaires ne travaille pas au parc Sea Life de Hawaï, il se consacre à son autre passion : les aventures sans lendemain avec de jolies touristes en mal de romantisme. Henry refuse toute liaison s&eacute;rieuse par peur de compromettre son rêve de partir en Alaska &eacute;tudier les morses...Pourtant, lorsqu'il rencontre Lucy, il est tout de suite fascin&eacute;. Enfreignant sa propre règle qui lui interdit de charmer des jeunes femmes du coin, Henry aborde Lucy, discute agr&eacute;ablement avec elle et obtient même un rendez-vous pour le lendemain.Lorsqu'il s'y pr&eacute;sente, Lucy ne le reconnaît pas et hurle à l'agression. Henry va d&eacute;couvrir que la jeune femme souffre d'une &eacute;trange maladie qui, chaque nuit, lui fait tout oublier. S'il veut vivre quelque chose avec elle, chaque jour devra être comme le premier...","amouretamnesie.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "The Boss Baby","Am&eacute;ricain","Tom McGrath","1:38","Stefan Godin,Vincent Ropion,Laurent Maurel","29 mars 2017","C'est toujours un choc de voir ses parents rentrer à la maison avec un b&eacute;b&eacute; dans les bras – surtout quand il porte une cravate, qu’il se balade avec un attach&eacute;-case et qu’il a la voix d’un quinquag&eacute;naire !Si Tim, 7 ans, ne voit pas d’un très bon œil ce «Baby Boss» d&eacute;barquer chez lui, il d&eacute;couvre qu’il a en r&eacute;alit&eacute; affaire à un espion et que lui seul peut l’aider à accomplir sa mission ultra secrète…Car Baby Boss se pr&eacute;pare à un affrontement titanesque entre les b&eacute;b&eacute;s et…. les toutous, charmants petits chiots qui vont bientôt être vendus pour remplacer les b&eacute;b&eacute;s dans le cœur des parents !","babyboss.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Badrinath Ki Dulhania","Indien","Shashank Khaitan","1:47","Alia Bhatt,Varun Dhawan,Gauhar Khan"," 10 mars 2017","Badrinath Bansal de Jhansi et Vaidehi Trivedi de Kota appartiennent à de petites villes mais ont des opinions diam&eacute;tralement oppos&eacute;es sur tout. Cela conduit à un conflit d'id&eacute;ologies, bien que les deux reconnaissent la bont&eacute; mutuelle.","badrinath.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "La Belle et la Bête","am&eacute;ricain","Bill Condon","2:09","Emma Watson,Dan Stevens,Luke Evans","22 mars 2017","Une nouvelle adaptation live du conte \"La Belle et la Bête\". Belle, jeune fille rêveuse et passionn&eacute;e de litt&eacute;rature, vit avec son père, un vieil inventeur farfelu. S'&eacute;tant perdu une nuit dans la fôret, ce dernier se r&eacute;fugie au château de la Bête, qui la jette au cachot. Ne pouvant supporter de voir son père emprisonn&eacute;, Belle accepte alors de prendre sa place, ignorant que sous le masque du monstre se cache un Prince Charmant tremblant d'amour pour elle, mais victime d'une terrible mal&eacute;diction.","beautyandthebeast.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Behaving Badly","am&eacute;ricain","Tim Garrick","01:37"," Nat Wolff, Selena Gomez, Elisabeth Shue","12 mars 2013","L'histoire d'un jeune homme et d'une jeune fille pris dans un tourbillon rock'n'roll.","behavingbadly.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "The Belko Experiment","Am&eacute;ricain"," Greg McLean","1:28","John Gallagher Jr.,Tony Goldwyn,Adria Arjona","18 juin 2016","Une entreprise am&eacute;ricaine d'Am&eacute;rique du Sud est myst&eacute;rieusement scell&eacute;e, et ses employ&eacute;s d&eacute;voilent leurs vraies natures lorsqu'il leur est ordonn&eacute;s de s'entretuer sous peine de mort.","belko.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Berlin Syndrome","Australien","Cate Shortland","1:52","Teresa Palmer,Max Riemelt,Matthias Habich","14 aout 2016","Alors qu'elle est en vacances à Berlin, une photographe australienne rencontre un homme charismatique. Après une nuit passionn&eacute;e, elle se r&eacute;veille enferm&eacute;e dans l'appartement de cet homme et r&eacute;alise qu'il a l'intention de ne jamais la laisser sortir.","berlinsyndrome.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Bruce Tout-Puissant","Am&eacute;ricain","Tom Shadyac","1:41","Jim Carrey, Jennifer Aniston, Morgan Freeman","3 septembre 2003","Bruce Nolan, reporter pour une c&eacute;lèbre chaîne de t&eacute;l&eacute;vision de Buffalo, est constamment de mauvaise humeur. Pourtant, il n'a aucune raison d'avoir cette attitude de grincheux : il est très c&eacute;lèbre, et il est aim&eacute; par une très jolie jeune femme, Grace.Un jour où tout se passe mal pour lui (il s'offre un superbe accident de voiture et se fait virer de la chaîne), Bruce s'emporte et se met en colère contre Dieu. Mais il est entendu par l'oreille divine, qui d&eacute;cide de prendre forme humaine et de descendre sur Terre. Dieu met au d&eacute;fi le reporter : il lui lègue les pouvoirs divins pendant une semaine et charge Bruce de faire mieux que lui. S'il &eacute;choue, il peut entraîner l'apocalypse...","brucealmighty.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Le Chihuahua De Beverly Hills","Am&eacute;ricain","Raja Gosnell","1:32","Jamie Lee Curtis, Piper Perabo, Nick Zano","25 mars 2009","Chlo&eacute;, une petite chienne Chihuahua de Beverly Hills toute pomponn&eacute;e se perd accidentellement dans les rues de Mexico. Pas le moindre spa, pas la moindre boutique de luxe à l'horizon... Seule pour la première fois de sa vie de petite chienne gât&eacute;e, Chlo&eacute; va heureusement trouver des amis inattendus pour l'aider : un berger allemand qui a grandi dans la rue, Delgado et un chiot &eacute;namour&eacute;, Papi. Tous deux lui tendront une patte secourable pour l'aider à d&eacute;couvrir en elle-même la force de retrouver sa maison.","chihuahua.jpg");


INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "CHiPs","Am&eacute;ricain","Dax Shepard","1:41","Michael Peña,Dax Shepard,Vincent D?Onofrio","1 août 2017","Le quotidien du brun t&eacute;n&eacute;breux Francis \"Ponch\" Poncherello et du blond jovial Jon Baker, deux motards de la police de la route californienne.","chips.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Cigognes et compagnie","Am&eacute;ricain"," Nicholas Stoller, Doug Sweetland","1:27","Florent Peyre, B&eacute;rengère Krief, Issa Doumbia, Jennifer Aniston, Ty Burrell","12 Octobre 2016","Pendant longtemps, les cigognes livraient les b&eacute;b&eacute;s. D&eacute;sormais, elles acheminent des colis pour un g&eacute;ant de l'Internet. Junior, coursier star de l'entreprise, s'apprête à être promu. Mais il actionne accidentellement la Machine à Fabriquer les B&eacute;b&eacute;s… qui produit une adorable petite fille, en totale infraction avec la loi !Avec l'aide de son ami Tulip, seul être humain sur le Mont Cigogne, Junior se pr&eacute;cipite pour effectuer sa toute première livraison de b&eacute;b&eacute;. Le temps presse car son patron ne tardera pas à apprendre la nouvelle… Junior pourra-t-il redonner aux cigognes la vraie mission qui est la leur ?","cigogneetcie.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Clochette Et La Cr&eacute;ature L&eacute;gendaire","Am&eacute;ricain","Steve Loter","1:16","Lorie Pester, Aliz&eacute;e, Ginnifer Goodwin","8 avril 2015","On raconte que les rugissements lointains qu?on entend parfois le soir seraient ceux d?une cr&eacute;ature myst&eacute;rieuse qui vivrait tapie dans un endroit recul&eacute;. Quand Noa rencontre une impressionnante cr&eacute;ature qu?elle ne connait pas, en bonne f&eacute;e des animaux, elle d&eacute;cide de mener l?enquête et de l?&eacute;tudier pour mieux percer son secret. Se pourrait-il que ce soit la bête de la l&eacute;gende . En effet l?&eacute;trange cr&eacute;ature ne ressemble à personne . elle est &eacute;norme avec des yeux verts brillants et elle s?avère des plus impressionnantes. Mais Noa sent que derrière l?effrayante apparence de la bête se cache un c?ur d?or. Elle va devoir convaincre Clochette et ses amies de prendre, avant qu?il ne soit trop tard, tous les risques pour la sauver?","clochette.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "The Croods","Am&eacute;ricain","Chris Sanders, Kirk De Micco","1:32","Nicolas Cage, Ryan Reynolds, Emma Stone","10 avril 2013","Lorsque la caverne où ils vivent depuis toujours est d&eacute;truite et leur univers familier r&eacute;duit en miettes, les Croodsse retrouvent oblig&eacute;s d?entreprendre leur premier grand voyage en famille. Entre conflits g&eacute;n&eacute;rationnelset bouleversements sismiques, ils vont d&eacute;couvrir un nouveau monde fascinant, rempli de cr&eacute;aturesfantastiques, et un futur au-delà de tout ce qu?ils avaient imagin&eacute;.Les Croodsprennent rapidement conscience que s?ils n?&eacute;voluentpas? ils appartiendront à l?Histoire","croods.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Devil?s Domain","Am&eacute;ricain","Jared Cohn","1:33","Michael Madsen, Madi Vodane, Linda Bella","19 mai 2017","Lisa est victime de harcèlement au lyc&eacute;e depuis qu'elle a r&eacute;v&eacute;l&eacute; son homosexualit&eacute;. Elle en devient anorexique. Le paroxysme est atteint lorsqu'une vid&eacute;o d'elle en train de vomir et de se masturber est diffus&eacute;e sur internet. Elle conclut alors un pacte avec le diable pour se venger.","devilsdomain.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "George Le Petit Curieux 3 : Retour Dans La Jungle","Am&eacute;ricain","Phil Weinstein","1:48","Angela Bassett, Jeff Bennett, John Goodman","12 juillet 2015","George le petit curieux se voit proposer une nouvelle mission un peu sp&eacute;ciale : une mission dans l'espace.","george3.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Insaisissables","Français","Louis Leterrier","1:56","Jesse Eisenberg,Mark Ruffalo,Woody Harrelson","31 juillet 2013","« Les Quatre Cavaliers », un groupe de brillants magiciens et illusionnistes, viennent de donner deux spectacles de magie &eacute;poustouflants : le premier en braquant une banque sur un autre continent, le deuxième en transf&eacute;rant la fortune d'un banquier v&eacute;reux sur les comptes en banque du public. Deux agents sp&eacute;ciaux du FBI et d'Interpol sont d&eacute;termin&eacute;s à les arrêter avant qu'ils ne mettent à ex&eacute;cution leur promesse de r&eacute;aliser des braquages encore plus audacieux. Ils font appel à Thaddeus, sp&eacute;cialiste reconnu pour expliquer les tours de magie les plus sophistiqu&eacute;s. Alors que la pression s'intensifie, et que le monde entier attend le spectaculaire tour final des Cavaliers, la course contre la montre commence.","insaisissables.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "John Wick 2","Am&eacute;ricain","Chad Stahelski","2:03","Keanu Reeves, Common, Laurence Fishburne","22 f&eacute;vrier 2017","John Wick est forc&eacute; de sortir de sa retraite volontaire par un de ses ex-associ&eacute;s qui cherche à prendre le contrôle d?une myst&eacute;rieuse confr&eacute;rie de tueurs internationaux. Parce qu?il est li&eacute; à cet homme par un serment, John se rend à Rome, où il va devoir affronter certains des tueurs les plus dangereux du monde.","johnwick2.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Kidnap","Am&eacute;ricain","Luis Prieto","1:35","Halle Berry,Dana Gourrier,Christopher Berry","13 juillet 2017","Une femme, dont le fils vient d'être enlev&eacute; dans un centre commercial, se met à la poursuite des ravisseurs afin de le r&eacute;cup&eacute;rer.NOTE: Le fichier sous titre &eacute;tait sans tag de la FANSUB je peut juste remercier celui qui a up le sous titre mrfeelgood.","kidnap.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "La Grande Muraille","Am&eacute;ricain","Zhang Yimou","2:00","Matt Damon,Pedro Pascal,Willem Dafoe","11 janvier 2017","L'ultime combat qu'une faction arm&eacute;e d'&eacute;lite livre au nom de l'humanit&eacute; sur les remparts de la muraille la plus c&eacute;lèbre du monde. ","lagrandemuraille.jpg");


INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Le Magicien d?Oz","Am&eacute;ricain"," Victor Fleming","1:42","Judy Garland, Frank Morgan, Ray Bolger","26 juin 1946","Dorothy, jeune orpheline, vit chez son oncle et sa tante. Tout irait pour le mieux si l'institutrice ne d&eacute;testait pas son chien. C'est alors que Dorothy fait un rêve où elle se trouve transport&eacute;e au royaume magique des Munchkins à la recherche de son chien. Les Munchkins sont des nains prot&eacute;g&eacute;s par la bonne f&eacute;e du Nord mais menac&eacute;s par la m&eacute;chante f&eacute;e de l'Ouest. Pour retrouver son chien, Dorothy doit s'emparer des chaussures rouges de la mauvaise f&eacute;e et aller voir le magicien d'Oz dans son palais d'Emeraude.","lemagiciendoz.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "LES ENFANTS LOUPS - AME & YUKI","Japon","Mamoru Hosoda","1:57","Kumiko Asô (Hotsuta no okusan (voice)) Megumi Hayashibara (Souhei?s Mother (voice)) Takuma Hiraoka (Souhei (voice)) Amon Kabe (Ame (child) (voice)) Mone Kamishiraishi ( (voice)) Tomie Kataoka (Nirasaki no Obaasan (voice))","12 octobre 2012","Hana Youshouki (« Fleur » ), une &eacute;tudiante âg&eacute;e de 19 ans, tombe amoureuse d'un &eacute;tudiant solitaire (Ookami Otoko) qui en vient à partager ses sentiments. Un soir, il lui r&eacute;vèle être un homme-loup. L'homme-loup donne à Hana deux enfants : une fille, Yuki (« Neige » ) puis un garçon, Ame (« Pluie » ), qui sont moiti&eacute; humains, moiti&eacute; louveteaux. Yuki est la plus vive et la plus volontaire des deux, sportive et gloutonne, tandis qu'Ame est fragile, maladroit, r&eacute;serv&eacute; et a un app&eacute;tit d'oiseau. Pendant un temps, la famille vit paisiblement à Tokyo où Hana cache sa nature lupine. Mais à la mort accidentelle de l?homme-loup à la naissance d'Ame, Hana est afflig&eacute;e et rencontrant des difficult&eacute;s croissantes à cacher le secret de ses enfants, d&eacute;cide de d&eacute;m&eacute;nager à la campagne.","lesenfantsloup.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Les Rebelles de la forêt","am&eacute;ricain","Jill Culton","1:30"," Martin Lawrence,Ashton Kutcher,Gary Sinise","12 fevrier 2005","Depuis toujours, l'homme a r&eacute;gn&eacute; sur la forêt. Mais cette fois, les choses vont changer... Boog, un ours apprivois&eacute; et heureux de l'être, va voir sa paisible existence boulevers&eacute;e par sa rencontre avec Elliot, un cerf sauvage aussi maigrichon que bavard. Elliot arrive à convaincre Boog de quitter sa vie de rêve pour aller \"vivre en libert&eacute; dans la nature\" et r&eacute;veiller ses instincts...","lesrebellesdelaforet.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Logan","Am&eacute;ricain","James Mangold","2:17","Hugh Jackman,Patrick Stewart,Dafne Keen","1 mars 2017","Dans un futur proche, un certain Logan, &eacute;puis&eacute; de fatigue, s’occupe d’un Professeur X souffrant, dans un lieu gard&eacute; secret à la frontière Mexicaine. Mais les tentatives de Logan pour se retrancher du monde et rompre avec son pass&eacute; vont s’&eacute;puiser lorsqu’une jeune mutante traqu&eacute;e par de sombres individus va se retrouver soudainement face à lui.","logan.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Mal&eacute;fique","Am&eacute;ricain","Robert Stromberg","1:37","Angelina Jolie,Elle Fanning,Sharlto Copley","28 mai 2014","Mal&eacute;fique est une belle jeune femme au coeur pur qui mène une  vie idyllique au sein d'une paisible forêt dans un royaume où règnent le bonheur et l'harmonie. Un jour, une arm&eacute;e d'envahisseurs menace les frontières du pays et Mal&eacute;fique, n'&eacute;coutant que son courage, s'&eacute;lève en f&eacute;roce protectrice de cette terre. Dans cette lutte acharn&eacute;e, une personne en qui elle avait foi va la trahir, d&eacute;clenchant en elle une souffrance à nulle autre pareille qui va petit à petit transformer son coeur pur en un coeur de pierre. Bien d&eacute;cid&eacute;e à se venger, elle s'engage dans une bataille &eacute;pique avec le successeur du roi, jetant une terrible mal&eacute;diction sur sa fille qui vient de naître, Aurore. Mais lorsque l'enfant grandit, Mal&eacute;fique se rend compte que la petite princesse d&eacute;tient la cl&eacute; de la paix du royaume, et peut-être aussi celle de sa propre r&eacute;demption...","malefique.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Marley & moi","Am&eacute;ricain","David Frankel","1:40","Owen Wilson,Jennifer Aniston,Eric Dane","4 mars 2009","Jenny et John viennent tout juste de se marier sous la neige du Michigan et d&eacute;cident de partir s'installer sous le soleil de Floride. Alors que l'envie d'avoir un premier enfant se profile chez Jenny, John espère retarder l'&eacute;ch&eacute;ance en lui offrant un adorable chiot sur les conseils avis&eacute;s de son collègue S&eacute;bastien, un s&eacute;ducteur profitant pleinement de son c&eacute;libat. C'est ainsi que Marley, un jeune labrador, prend place au sein du couple. En grandissant, l'animal se r&eacute;vèle aussi craquant que d&eacute;vastateur et la maison devient un v&eacute;ritable terrain de jeu, où plus rien ne peut &eacute;chapper à sa voracit&eacute;. Mais l'envie de fonder une famille ressurgit, et Jenny attend d&eacute;sormais son premier enfant. Au rythme des ann&eacute;es et des catastrophes qu'il provoque, Marley sera le t&eacute;moin d'une famille qui se construit et s'agrandit, devant faire face à des choix de carrière, des p&eacute;riodes de doute et des changements de vie. Pour Jenny et John, même si Marley est le pire chien du monde, cette tornade d'&eacute;nergie leur t&eacute;moignera une affection et une fid&eacute;lit&eacute; sans limite, pour leur enseigner la plus grande leçon de leur vie.","marleyetmoi.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Les Miller, Une Famille En Herbe","Am&eacute;ricain","Rawson Marshall Thurber","1:50","Jennifer Aniston, Jason Sudeikis, Will Poulter","18 septembre 2013","David Burke est un dealer à la petite semaine qui se contente de vendre sa marchandise à des chefs cuisiniers et des mamans accompagnant leurs fils au football, mais pas à des ados – car, au fond, il a quand même des principes ! Alors que tout devrait se passer au mieux pour lui, les ennuis s’accumulent… Pr&eacute;f&eacute;rant garder profil bas pour des raisons &eacute;videntes, David comprend, à son corps d&eacute;fendant, qu’on peut subir la pire injustice même lorsqu’on est anim&eacute; des meilleures intentions : tentant de venir en aide à des jeunes du quartier, il se fait agresser par trois voyous qui lui volent sa marchandise et son argent. Il se retrouve dans une situation des plus d&eacute;licates puisqu’il doit d&eacute;sormais rembourser son fournisseur, Brad. Afin d’&eacute;ponger sa dette – et de rester en vie –, David n’a d’autre choix que de jouer dans la cour des grands en se rendant au Mexique pour ramener une importante cargaison de drogue à Brad. R&eacute;ussissant à convaincre ses voisins – Rose, une strip-teaseuse cynique, Kenny, qui aimerait bien tester la marchandise et Casey, une ado d&eacute;brouillarde couverte de tatouages et de piercings – de lui venir en aide, il met au point un plan cens&eacute; être infaillible : avec ses complices qu’il fait passer pour sa femme et ses deux grands enfants, il met le cap sur le Mexique au volant d’un camping-car flambant neuf le jour de la fête nationale. Ce week-end risque bien d’être explosif…","miller.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Peelers","Canadien","Sev&eacute; Schelenz","1:35","Wren Walker, Caz Odin Darko, Madison J. Loos","28 Mars 2017","Dans le strip-club d'une petite ville, une terrrrrrrible infection cr&eacute;edes tueurs-fous-sanguinaires qui vont d&eacute;cimer des demoiselles peu (pas) vêtues...","peelers.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Pirates des Caraïbes : La Mal&eacute;diction du Black Pearl","Am&eacute;ricain","Gore Verbinski","2:20","Johnny Depp,Geoffrey Rush,Orlando Bloom","13 août 2003","Dans la mer des Caraïbes, au XVIIe siècle, Jack Sparrow, flibustier gentleman, voit sa vie idylle basculer le jour où son ennemi, le perfide capitaine Barbossa, lui vole son bateau, le Black Pearl, puis attaque la ville de Port Royal, enlevant au passage la très belle fille du gouverneur, Elizabeth Swann. L'ami d'enfance de celle-ci, Will Turner, se joint à Jack pour se lancer aux trousses du capitaine. Mais Will ignore qu'une mal&eacute;diction frappe Barbossa et ses pirates. Lorsque la lune brille, ils se transforment en morts-vivants. Leur terrible sort ne prendra fin que le jour où le fabuleux tr&eacute;sor qu'ils ont amass&eacute; sera restitu&eacute;...","piratesdescaraibes1.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Pirates des Caraïbes : le Secret du Coffre Maudit","Am&eacute;ricain","Gore Verbinski","2:30","Johnny Depp,Orlando Bloom,Keira Knightley","2 août 2006","Dans ce nouvel opus de l'aventure Pirates des Caraïbes, le toujours aussi excentrique pirate Jack Sparrow est confront&eacute; subitement à son pass&eacute;. Treize ans auparavant, Jack signait un pacte avec Davey Jones, le maître des sept mers, dont l'esprit mal&eacute;fique n'a d'&eacute;gal que son apparence tentaculaire. En &eacute;change de son âme, ce dernier lui promettait le commandement du mythique Black Pearl...Aujourd'hui, Jones vient donc r&eacute;cup&eacute;rer sa dette. Mais donner son âme à Jones est sans issue, il n'y a pas de r&eacute;demption possible, c'est devenir comme tous les membres de son &eacute;quipage maudit, un fantôme au physique aussi repoussant que terrifiant. Pour &eacute;viter ce sort funeste auquel Jack ne tient pas vraiment, il n'a qu'une solution : retrouver le coffre maudit de Jones où sont cach&eacute;s les âmes emprisonn&eacute;es...","piratesdescaraibes2.jpg");

INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Pirates des Caraïbes : Jusqu?au Bout du Monde","Am&eacute;ricain","Gore Verbinski","2:48","Johnny Depp,Orlando Bloom,Keira Knightley","23 mai 2007","L'âge d'or de la piraterie touche à sa fin. Même le terrifiant Vaisseau Fantôme et son capitaine maudit Davy Jones servent à pr&eacute;sent Lord Cutler Beckett et la Compagnie anglaise des Indes Orientales. L'invincible Hollandais Volant &eacute;cume d&eacute;sormais les sept mers, massacrant sans piti&eacute; pirates de tous bords et sabordant leurs navires.Will Turner, Elizabeth Swann et le capitaine Barbossa n'ont qu'une seule chance de r&eacute;sister à Beckett et à son armada destructrice : ils doivent rassembler les Neuf Seigneurs de la Cour des Frères, mais l'un des membres les plus &eacute;minents, le capitaine Jack Sparrow, manque à l'appel.Will, Elizabeth et Barbossa, second&eacute;s par Tia Dalma, Pintel et Ragetti, doivent faire voile vers des mers orientales inconnues, pour affronter un pirate chinois, le capitaine Sao Feng, et s'emparer des cartes qui les conduiront au-delà des limites du monde connu, là où Jack est retenu...","piratesdescaraibes3.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Pirates des Caraïbes : la Fontaine de Jouvence","Am&eacute;ricain"," Rob Marshall","2:20","Johnny Depp,Pen&eacute;lope Cruz,Geoffrey Rush","18 mai 2011","Dans cette histoire pleine d'action, où v&eacute;rit&eacute;, trahison, jeunesse &eacute;ternelle et mort forment un cocktail explosif, le capitaine Jack Sparrow retrouve une femme qu'il a connue autrefois. Leurs liens sont-ils faits d'amour ou cette femme n'est-elle qu'une aventurière sans scrupules qui cherche à l'utiliser pour d&eacute;couvrir la l&eacute;gendaire Fontaine de Jouvence . Lorsqu'elle l'oblige à embarquer à bord du Queen Anne's Revenge, le bateau du terrible pirate Barbe-Noire, Jack ne sait plus ce qu'il doit craindre le plus : le redoutable maître du bateau ou cette femme surgie de son pass&eacute;...","piratesdescaraibes4.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Pirates des Caraïbes : la Vengeance de Salazar","Am&eacute;ricain","Joachim Ranning","2:09","Johnny Depp,Javier Bardem,Brenton Thwaites","24 mai 2017","Les temps sont durs pour le Capitaine Jack, et le destin semble même vouloir s’acharner lorsqu’un redoutable &eacute;quipage fantôme men&eacute; par son vieil ennemi, le terrifiant Capitaine Salazar, s’&eacute;chappe du Triangle du Diable pour an&eacute;antir tous les flibustiers &eacute;cumant les flots… Sparrow compris ! Le seul espoir de survie du Capitaine Jack est de retrouver le l&eacute;gendaire Trident de Pos&eacute;idon, qui donne à celui qui le d&eacute;tient tout pouvoir sur les mers et les oc&eacute;ans. Mais pour cela, il doit forger une alliance pr&eacute;caire avec Carina Smyth, une astronome aussi belle que brillante, et Henry, un jeune marin de la Royal Navy au caractère bien tremp&eacute;. À la barre du Dying Gull, un minable petit rafiot, Sparrow va tout entreprendre pour contrer ses revers de fortune, mais aussi sauver sa vie face au plus implacable ennemi qu’il ait jamais eu à affronter…","piratesdescaraibes5.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Polly et moi","Am&eacute;ricain","John Hamburg","1:30","Ben Stiller,Jennifer Aniston,Philip Seymour Hoffman","10 mars 2004","Reuben Feffer est l'homme le plus prudent, le plus routinier du monde. Planifiant sa vie et sa carrière d'assureur avec une rigueur toute math&eacute;matique, il se d&eacute;fie comme la peste de toute surprise, bonne ou mauvaise. L'insouciante Polly Prince navigue à vue, improvise au jour le jour, multiplie les paris et les coups de tête. Qu'importe : les occasions ne manquent pas, il y a toujours quelque part un nouveau job, un nouvel amour, un nouvel appartement dans une nouvelle ville.Deux surprises de taille viennent troubler la vie si ordonn&eacute;e de Reuben Feffer. La première : sa femme le trompe et le plaque en pleine lune de miel. La seconde : il rencontre Polly à une r&eacute;ception, la trouve charmante, irr&eacute;sistiblement drôle et s&eacute;duisante, se souvient qu'ils firent ensemble leurs &eacute;tudes secondaires et qu'elle &eacute;tait, comme lui, un modèle de s&eacute;rieux. Aucune raison de penser qu'elle ait chang&eacute;...","pollyetmoi.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "RAID Dingue","français","Dany Boon","1:45","Alice Pol,Dany Boon,Michel Blanc","1 f&eacute;vrier 2017","Johanna Pasquali est une fliquette pas comme les autres. Distraite, rêveuse et maladroite, elle est une policière sympathique mais totalement nulle. Dot&eacute;e pourtant de r&eacute;elles comp&eacute;tences, sa maladresse fait d'elle une menace pour les criminels. Assign&eacute;e à des missions aussi dangereuses que des voitures mal gar&eacute;es ou des vols à l'&eacute;talage, elle s'entraîne sans relâche pendant son temps libre pour r&eacute;aliser son rêve : être la première femme à int&eacute;grer le groupe d'&eacute;lite du RAID. Accept&eacute;e au centre de formation du RAID, elle se retrouve alors avec l'agent Eugène Froissard (dit Poissard), le plus misogyne des agents du RAID. Ce duo improbable se voit charg&eacute; d'arrêter le redoutable Gang des L&eacute;opards. Mais avant de pouvoir les arrêter, il faudrait d&eacute;jà qu\"ils parviennent à travailler en binôme sans s'entretuer au cours des entraînements..","raiddingue.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Le Retour Des Sorciers : Alex Contre Alex","Am&eacute;ricain"," Victor Gonzalez","1:59"," Selena Gomez, Jake T. Austin, Jennifer Stone, Gregg Sulkin, Beau Mirchoff","22 mai 2013","Un an après être devenue la sorcière de la famille, Alex n'a toujours pas le droit d'utiliser la magie de façon libre. Elle jette alors un sort qui la fera se diviser en deux, la bonne Alex et l'Alex mal&eacute;fique. Dominique, un sorcier de Wiztech, tombe amoureux de la bonne Alex mais elle le rejette à cause de sa relation avec Mason. Le sorcier italien se r&eacute;vèle être le mal qui souhaite de se d&eacute;barrasser de tous les mortels afin de r&eacute;gner sur le monde, et l'Alex mal&eacute;fique s'associe avec lui. La bonne Alex tente de sauver le monde tandis que l'Alex mal&eacute;fique tente de le conqu&eacute;rir.","retourdessorciers.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Scooby-Doo et l?&eacute;cole des sorcières","Am&eacute;ricain","Charles A Nichols","1:45"," Sheryl Benko, Stephen Jones, Philip A. Patterson","12 mars 2000","Scooby-Doo et Sammy sont employ&eacute;s comme professeurs dans un collège sp&eacute;cialis&eacute; pour les enfants de monstres. D'abord terroris&eacute;s, nos h&eacute;ros finissent par s'attacher à leurs &eacute;lèves et quand un groupe est enlev&eacute; par la sorcière Reevolta, ils volent à leur rescousse ...","scoobydoo.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Sensoria","Su&eacute;dois","Christian Hallman","1:21","Lanna Ohlsson, Norah Andersen, Alida Morberg","25 January 2016","Caroline, bientôt 40 ans, a perdu à peu tout ce à quoi elle tenait dans la vie. Elle s'installe dans un nouvel appartement et r&eacute;alise qu'elle n'est pas aussi seule qu'elle ne le pensait. Alors qu'elle est à la recherche de quelque chose de neuf dans sa vie, quelque chose semble aussi à sa recherche...","sensoria.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Seuls","français","David Moreau","1:30","Sofia Lesaffre,St&eacute;phane Bak,Jean-Stan du Pac"," 8 f&eacute;vrier 2017","Leïla, 16 ans, se r&eacute;veille en retard comme tous les matins. Sauf qu'aujourd'hui, il n'y a personne pour la presser. Où sont ses parents? Elle prend son v&eacute;lo et traverse son quartier, vide. Tout le monde a disparu. Se pensant l'unique survivante d'une catastrophe inexpliqu&eacute;e, elle finit par croiser quatre autres jeunes: Dodji, Yvan, Camille et Terry. Ensemble, ils vont tenter de comprendre ce qui est arriv&eacute;, apprendre à survivre dans leur monde devenu hostile? Mais sont-ils vraiment seuls?","seuls.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Shimmer Lake","Am&eacute;ricain"," Oren Uziel","1:23","Wyatt Russell,Rainn Wilson,Benjamin Walker"," 9 juin 2017","Remontant le temps jour par jour, ce thriller à l'humour noir suit un sh&eacute;rif local tandis qu'il traque les trois suspects d'un braquage de banque, dont son frère.","shimmerlake.jpg");

INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Suite française","français","Saul Dibb","1:47","Michelle Williams, Kristin Scott Thomas, Matthias Schoenaerts","1 avril 2015","ann&eacute;e 1940. France. Dans l'attente de nouvelles de son mari prisonnier de guerre, Lucile Angellier m?ne une existence soumise sous l'oeil inquisiteur de sa belle-m?re. L'arriv?e de l'arm?e allemande dans leur village contraint les deux femmes ? loger chez elles le lieutenant Bruno von Falk. Lucile tente de l'?viter mais ne peut bient?t plus ignorer l'attirance qu'elle ?prouve pour l'officier...","suitefrancaise.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Territory 8","Am&eacute;ricain","Kelly Schwarze","1:21","Michael A. Tushaus, Heung Wong, Colin Warner Wallace","4 f&eacute;vrier 2015","Lorsqu'une explosion chimique &eacute;clate, deux scientifiques exerçant dans une base secrète se retrouvent condamn&eacute;s dans une zone de quarantaine. Leur entreprise souhaite effacer toute preuve de leur implication dans la catastrophe, y compris en assassinant les t&eacute;moins. Les deux hommes vont tout faire pour sortir des locaux sains et saufs pour r&eacute;v&eacute;ler les d&eacute;tails de leurs exp&eacute;riences...","territory8.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "The Hunter?s Prayer","Am&eacute;ricain","Jonathan Mostow","1:57"," Sam Worthington,Odeya Rush","12 septembre 2017","Un tueur à gages aide une jeune fille à venger la mort de ses parents...","thehuntersprayer.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Les Stagiaires","Am&eacute;ricain","Shawn Levy","2:00","Vince Vaughn,Owen Wilson,Rose Byrne","26 juin 2013","Billy et Nick, deux quarantenaires dont les carrières ont &eacute;t&eacute; pulv&eacute;ris&eacute;es par Internet, repartent à z&eacute;ro en obtenant un stage chez Google, qui peut-être, d&eacute;bouchera sur un job. En comp&eacute;tition avec des petits g&eacute;nies de l'informatique tout droit sortis de l'&eacute;cole, ils vont devoir prouver qu'ils ne sont pas des dinosaures...","theinternship.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "TOM & JERRY ET LE MAGICIEN D?OZ","Am&eacute;ricain","Spike Brandt, Tony Cervone","1:21","Grey Griffin, Amy Pemberton, Joe Alaskey ","17 août 2016","Tom et Jerry profitent de la tranquillit&eacute; d'une petite ferme du Texas avec Dorothy, son chien Toto et sa famille. Mais lorsqu'une tornade vient secouer ce havre de paix et emmène Dorothy dans un monde magique, Tom et Jerry partent à la recherche de leur amie.","tomandjerrybacktooz.jpg"); 
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Vaiana, la l&eacute;gende du bout du monde","Am&eacute;ricain","John Musker","1:47","Cerise Calixte,Anthony Kavanagh,Mareva Galanter","30 novembre 2016","Il y a 3 000 ans, les plus grands marins du monde voyagèrent dans le vaste oc&eacute;an Pacifique, à la d&eacute;couverte des innombrables îles de l'Oc&eacute;anie. Mais pendant le mill&eacute;naire qui suivit, ils cessèrent de voyager. Et personne ne sait pourquoi...Vaiana, la l&eacute;gende du bout du monde raconte l'aventure d'une jeune fille t&eacute;m&eacute;raire qui se lance dans un voyage audacieux pour accomplir la quête inachev&eacute;e de ses ancêtres et sauver son peuple. Au cours de sa travers&eacute;e du vaste oc&eacute;an, Vaiana va rencontrer Maui, un demi-dieu. Ensemble, ils vont accomplir un voyage &eacute;pique riche d'action, de rencontres et d'&eacute;preuves... En accomplissant la quête inaboutie de ses ancêtres, Vaiana va d&eacute;couvrir la seule chose qu'elle a toujours cherch&eacute;e : elle-même.","vaiana.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Vice Versa","Am&eacute;ricain","Pete Docter","1:35","Charlotte Le Bon,Pierre Niney,M&eacute;lanie Laurent","17 juin 2015","Au Quartier G&eacute;n&eacute;ral, le centre de contrôle situ&eacute; dans la tête de la petite Riley, 11 ans, cinq Émotions sont au travail. À leur tête, Joie, d&eacute;bordante d'optimisme et de bonne humeur, veille à ce que Riley soit heureuse. Peur se charge de la s&eacute;curit&eacute;,  Colère s'assure que la justice règne, et D&eacute;goût empêche Riley de se faire empoisonner la vie  au sens propre comme au figur&eacute;. Quant à Tristesse, elle n'est pas très sûre de son rôle. Les autres non plus, d'ailleurs... Lorsque la famille de Riley emm&eacute;nage dans une grande ville, avec tout ce que cela peut avoir d'effrayant, les Émotions ont fort à faire pour guider la jeune fille durant cette difficile transition. Mais quand Joie et Tristesse se perdent accidentellement dans les recoins les plus &eacute;loign&eacute;s de l'esprit de Riley, emportant avec elles certains souvenirs essentiels, Peur, Colère et D&eacute;goût sont bien oblig&eacute;s de prendre le relais. Joie et Tristesse vont devoir s'aventurer dans des endroits très inhabituels comme la M&eacute;moire à long terme, le Pays de l'Imagination, la Pens&eacute;e Abstraite, ou la Production.","viceversa.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Les Sorciers de Waverly Place : Le film","Am&eacute;ricain","Lev L. Spiro","1:45","Selena Gomez,David Henrie,Jake T. Austin","15 juin 2009","Le voyage de la famille Russo pour Porto Rico aurait dû être un voyage de rêve. Les parents ont choisi de faire d&eacute;couvrir à leurs enfants l'île sur laquelle ils se sont rencontr&eacute;s et où ils sont tomb&eacute;s amoureux. Paysages paradisiaques et souvenirs magiques &eacute;taient alors au programme. Mais attention, toute baguette magique, grimoire et autres potions magiques doivent rester à New-York : ces vacances se passeront sans magie... Justin d&eacute;cide tout de même d'emmener sa baguette, on ne sait jamais ! A peine arriv&eacute;e à Porto Rico, Alex, bien d&eacute;cid&eacute;e à profiter de ces vacances pour se faire de nouveaux amis, promet de se rendre à une fête organis&eacute;e sur la plage, et compte bien sur la magie pour parvenir à ses fins. Malheureusement sa mère s'y oppose et une dispute &eacute;clate. Sans r&eacute;fl&eacute;chir, Alex jette par accident un sort à sa mère : 'Je voudrais que Papa et toi vous ne vous soyez connus !'... Son voeu se r&eacute;alise et menace la famille : les parents, Jerry et Theresa ne se souviennent plus l'un de l'autre, comme avant leur rencontre. Pour conjurer le sort, Alex et Justin devront trouver dans la jungle la Pierre des Rêves pendant que Max devra trouver un moyen de faire retomber ses parents amoureux l'un de l'autre. Le temps presse, les 3 enfants Russo n'ont que 48.","wizardsofwaverlyplace.jpeg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Wonder Woman","Am&eacute;ricain","Patty Jenkins","2:21","Gal Gadot,Chris Pine,Connie Nielsen","7 juin 2017","C'&eacute;tait avant qu'elle ne devienne Wonder Woman, à l'&eacute;poque où elle &eacute;tait encore Diana, princesse des Amazones et combattante invincible. Un jour, un pilote am&eacute;ricain s'&eacute;crase sur l'île paradisiaque où elle vit, à l'abri des fracas du monde. Lorsqu'il lui raconte qu'une guerre terrible fait rage à l'autre bout de la planète, Diana quitte son havre de paix, convaincue qu'elle doit enrayer la menace. En s'alliant aux hommes dans un combat destin&eacute; à mettre fin à la guerre, Diana d&eacute;couvrira toute l'&eacute;tendue de ses pouvoirs… et son v&eacute;ritable destin.","wonderwoman.jpg");
INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "xXx : Reactivated","Am&eacute;ricain","D.J. Caruso","1:47","Vin Diesel, Donnie Yen, Deepika Padukone, Kris Wu, Ruby Rose","18 Janvier 2017","Xander Cage, sportif de l?extrême devenu agent d'&eacute;lite, sort de l?exil qu?il s?&eacute;tait impos&eacute;, pour affronter le redoutable guerrier alpha Xiang et son &eacute;quipe. Il entre dans une course impitoyable afin de r&eacute;cup&eacute;rer une arme de destruction massive connue sous le nom de Boîte de Pandore. Recrutant une toute nouvelle &eacute;quipe d?experts accros à l'adr&eacute;naline, Xander se retrouve au coeur d?une conspiration menaçant les gouvernements les plus puissants du monde.","xxxreactivated.jpg");

INSERT INTO film (titre,origine,realisation,duree,acteurs,datesortie,description,cheminimg) VALUES ( "Zapped Une application d?enfer !","Am&eacute;ricain","Peter DeLuise","01:42"," Zendaya Coleman, Chanelle Peloso, Spencer Boldman","12 avril 2014","Zoey Stevens, 16 ans, danseuse dou&eacute;e et première de la classe a du mal à s?adapter à sa nouvelle &eacute;cole,son &eacute;quipe de danse, son nouveau beau-père, ses demi-frères turbulents et son chien indisciplin&eacute;. Mais les choses changent quand une application sur son t&eacute;l&eacute;phone commence à contrôler tous les garçons autour d?elle.","zapped.jpg");

/* liaison de categorie et film   INTO linkFilmCat (idCat, idFilm) VALUES*/
insert INTO linkFilmCat (idCat, idFilm) VALUES (,);

/* salle INTO salle (nom, numero, nbrPlac) VALUES*/
insert INTO salle (nom, numero, nbrPlac) VALUES ("",,);

/* programme INTO programme (idFilm, idSalle, daty, heureDebut, heureFin, prixUnitaire, prioritaire) VALUES*/
insert INTO programme (idFilm, idSalle, daty, heureDebut, heureFin, prixUnitaire, prioritaire) VALUES (,,"","","",,);

/* membre INTO membre (pseudo, email, password, autorisation, cheminimg) VALUES*/
insert INTO membre (pseudo, email, password, autorisation, cheminimg) VALUES ("","","",,"");

/* reservation INTO membre (idMembre, idProgramme, nbrPlac, montant) VALUES*/
insert INTO reservation (idMembre, idProgramme, nbrPlac, montant) VALUES (,,,);

/* commentaires INTO commentaires (idFilm, texte, idMembre) VALUES*/
insert INTO commentaires (idFilm, texte, idMembre) VALUES (,"",);

/* billet INTO billet (idReservation) VALUES*/
insert INTO billet (idReservation) VALUES ();




